create db, frame command
alanbernstein/pilosa pull request #1
Opened 2017-04-27 15:29 UTC by linhvo

my update just in process_query and createSingleOutput, other changes just a format. Should we use the same format for function (underscore or lower/upper case)

2017-04-27 23:12 UTC, alanbernstein commented
We should add some minimal validation, and maybe error messages, to handle cases like:

`:create index` sends a request with index name = "undefined", which succeeds but shouldn't
`:create` or `:unknown` send a request with undefined method(?)

2017-04-27 23:12 UTC, alanbernstein requested changes

2017-04-27 23:12 UTC, alanbernstein commented on webui/assets/main.js
> +                    switch (command) {
It looks like this can be done just once, outside the `command_type` switch. this change would require a check before sending the request, which we should be doing anyway

2017-04-27 23:44 UTC, alanbernstein commented
Yes we should be consistent with function and variable name styles. If there is a convention for javascript we should use that.

2017-04-28 13:57 UTC, alanbernstein commented on webui/assets/main.js
> +            // probably separate to a different function when option getting bigger
maybe we can split this out to a `parse_query` function, which returns an object including:
method: POST, GET, DELETE, none
endpoint
data
callback

then `:use indexname` can result in method: none, callback: update_index_dropdown

2017-04-28 14:42 UTC, linhvo commented on webui/assets/main.js
> +                    switch (command) {
yeah, I did that at the first place, then I thought there's many duplicated code when I did command_type inside command. But I agree that it's more reasonable to put command outside the command_type switch. I will revise back to the original way

2017-05-02 17:21 UTC, closed without merging